version: '3'
services: 
  web:
    build: .
    volumes:
      - .:/rails_test
    working_dir: /rails_test
    entrypoint:
      - /bin/sh
    stdin_open: true
    tty: true
    ports: ['3000:3000']
